// Uganda lakes - high-resolution data from OpenStreetMap and Natural Earth
// Data loaded from JSON generated by process-uganda-lakes.test.ts

import ugandaLakesData from "./uganda-lakes.json";

export interface UgandaLakeData {
  name: string;
  coordinates: [number, number][];
}

export const UGANDA_LAKES: UgandaLakeData[] = ugandaLakesData as UgandaLakeData[];
